using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections.ObjectModel;
using System.IO.Ports;

namespace ASCOM.LunaticAstro.FilterWheel.FilterWheelDriver.ViewModel
{
    internal partial class SetupViewModel : ObservableObject
    {
        // ------------------------------------------------------------
        // EVENTS
        // ------------------------------------------------------------

        /// <summary>
        /// Raised when the UI requests the dialog to close.
        /// The bool indicates OK (true) or Cancel (false).
        /// </summary>
        public event Action<bool>? CloseRequested;


        // ------------------------------------------------------------
        // PROPERTIES (auto-generated by CommunityToolkit)
        // ------------------------------------------------------------

        [ObservableProperty]
        private ObservableCollection<string> comPorts = new();

        [ObservableProperty]
        private string? selectedComPort;

        [ObservableProperty]
        private bool traceEnabled;


        // ------------------------------------------------------------
        // CONSTRUCTOR
        // ------------------------------------------------------------

        public SetupViewModel()
        {
            LoadComPorts();
            LoadSettings();
        }


        // ------------------------------------------------------------
        // INITIALISATION
        // ------------------------------------------------------------

        private void LoadComPorts()
        {
            ComPorts.Clear();
            foreach (var port in SerialPort.GetPortNames())
                ComPorts.Add(port);

            // Auto-select last used port if available
            if (ComPorts.Count > 0)
                SelectedComPort = ComPorts[0];
        }

        private void LoadSettings()
        {
            // TODO: Load from ASCOM Profile
            // Example:
            // SelectedComPort = Profile.GetValue("COMPort");
            // TraceEnabled = Profile.GetBool("TraceEnabled");

            TraceEnabled = false;
        }


        // ------------------------------------------------------------
        // COMMANDS
        // ------------------------------------------------------------

        [RelayCommand]
        private void Ok()
        {
            SaveSettings();
            CloseRequested?.Invoke(true);
        }

        [RelayCommand]
        private void Cancel()
        {
            CloseRequested?.Invoke(false);
        }


        // ------------------------------------------------------------
        // SAVE SETTINGS
        // ------------------------------------------------------------

        private void SaveSettings()
        {
            // TODO: Save to ASCOM Profile
            // Example:
            // Profile.SetValue("COMPort", SelectedComPort);
            // Profile.SetBool("TraceEnabled", TraceEnabled);
        }
    }
}